### ISSUE TITLE
为什么程序不默认调用GPU？

### ISSUE THREAD

**Issue by zdaoguang** [bojone/oppo-text-match#2]
苏神，这个bojone.py运行，不能直接调用GPU，应该如何调用呀？

**Comment by bojone** [comment]
因为根本不存在这回事。

GPU还是CPU，是你自己搭环境的事，bert4keras不是一个深度学习框架，只是一个调用深度学习框架（tensorflow）的框架。

综上所述：检查你的tf的gpu环境搭建好了没。

**Comment by jt120** [comment]
tf1.5支持cuda10.0，推测是你cuda版本装错了
