### ISSUE TITLE
简单脚本问题咨询

### ISSUE THREAD

**Issue by ArlanCooper** [bojone/oppo-text-match#7]
您好,我有以下问题想要咨询一下哈：
1.  random_mask 函数中，else 里面的 为什么output_ids 赋值为0呢？不太理解哈
2. 加载预训练的时候，build_transformer_model，keep_tokens=[0, 100, 101, 102, 103, 100, 100] 这几个数字代表的是什么意思呢？
3. bert4keras 的帮助文档哪里有呢?我看官方的说明文档都没有您调用的相关参数，但是您这边可以添加很多自己的参数，您是通过读源码知道的吗？

不好意思哈，我是NLP小白，所以问题的问题有点多和基础哈

**Comment by bojone** [comment]
1、用0和非0来标记哪部份是要预测的；
2、代表对应的token在原词表中的位置，用来给新模型做初始化；
3、bert4keras是我写的，我自然知道怎么用...
4、很遗憾没有很详细的帮助文章，我主要通过例子来介绍使用方式（ https://github.com/bojone/bert4keras/tree/master/examples ）。

**Comment by ArlanCooper** [comment]
> 1、用0和非0来标记哪部份是要预测的；
> 2、代表对应的token在原词表中的位置，用来给新模型做初始化；
> 3、bert4keras是我写的，我自然知道怎么用...
> 4、很遗憾没有很详细的帮助文章，我主要通过例子来介绍使用方式（ https://github.com/bojone/bert4keras/tree/master/examples ）。

好的，非常感谢您的解答
